### ISSUE TITLE
extending a pipeline to multiple templates with parameterised condition

### ISSUE THREAD

**Issue by Sheelayathakula** [soccerjoshj07/pipeline-templates#4]
Hello,

I have a question regarding extending a template. I want to create a jar or containerised image based on the parameterised condition.

for example: 

if ${{ parameters.x }}', 'True
extends:
    template: x/create-library.yml
{{ else }}:
extends:
    template: x/create-image.yml

I havent tested this yet.

**Comment by joshjohanning** [comment]
@Sheelayathakula I tested this out quick, and according to the pipeline editor/validator, this doesn't work 😢 

This example sees duplicate entry errors for the 2 `extends:` properties:
```yml
${{ if eq(variables.foo, 'adaptum') }}:
  extends:
    template: template/extends.yml
    parameters:
      usersteps:
      - script: echo "This is my first step"
      - script: echo "This is my second step"
${{ if eq(variables.foo, 'other') }}:
  extends:
    template: template/extends.yml
    parameters:
      usersteps:
      - script: echo "This is my first step"
      - script: echo "This is my second step"
```

I see duplicate entry errors for `template` and `parameters` for this example too:

```yml
extends:
  ${{ if eq(variables.foo, 'adaptum') }}:
    template: template/extends.yml
    parameters:
      usersteps:
      - script: echo "This is my first step"
      - script: echo "This is my second step"
  ${{ if eq(variables.foo, 'other') }}:
    template: template/extends.yml
    parameters:
      usersteps:
      - script: echo "This is my first step"
      - script: echo "This is my second step"
```


You would probably have to key on the parameter itself for the extends template path, something like:


```yml
extends:
  template: template/${{ parameters.x }}.yml
  parameters:
    usersteps:
    - script: echo "This is my first step"
    - script: echo "This is my second step"
```

As a reference, I have more information on the `extends` template in blog post from a few years ago here: https://josh-ops.com/posts/extends-template/ (I don't discuss conditionals, though)
